name: Node.js Package

on:
  push:
    branches:
      - main

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Install dependencies
        run: npm i
      - name: Configure NPM
        run: npm config set '//npm.pkg.github.com/:_authToken' "${GITHUB_TOKEN}"
      - name: Release version
        run: npx semantic-release
